name: currency_exchange
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.8

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.3
  dio: ^4.0.0
  get_it: ^7.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  either_dart: ^1.0.0
  google_fonts: ^6.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  bloc_test: ^9.1.5
  mocktail: ^1.0.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
